### ISSUE TITLE
🐛 [BUG] Breaks Vite building

### ISSUE THREAD

**Issue by zhyupe** [antvis/L7Plot#102]
### 🐛 Bug description [Please make everyone to understand it]

This package, which is a dependency of @ant-design/charts, breaks Vite building with following error:

```
$ vite build
vite v2.6.14 building for production...
✓ 35 modules transformed.
[vite:resolve] Failed to resolve entry for package "@antv/l7plot". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@antv/l7plot". The package may have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "@antv/l7plot". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@antv/l7plot". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (/Volumes/Projects/workspace/sample/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:30273:11)
    at resolvePackageEntry (/Volumes/Projects/workspace/sample/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:30269:9)
    at tryNodeResolve (/Volumes/Projects/workspace/sample/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:30044:11)
    at Object.resolveId (/Volumes/Projects/workspace/sample/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:29910:28)
    at /Volumes/Projects/workspace/sample/node_modules/rollup/dist/shared/rollup.js:22706:25
error Command failed with exit code 1.
```

- _Required_ **Link to minimal reproduction**: https://github.com/zhyupe/sample-vite-project

### 📷 Step to reproduce

```
yarn
yarn build
```

### 🏞 Expected result

Built without error.

### 🚑 Any additional [like screenshots]

Dependency Path:
![image](https://user-images.githubusercontent.com/2197479/143555851-cc7e1b89-771e-4d6b-9bd9-fde25f80bf18.png)

`package.json` of this package from unpkg, which declares an invalid 'module' that does not exist:
![image](https://user-images.githubusercontent.com/2197479/143555947-6db49d6c-bba4-4f9a-8b62-21c58f2e26d1.png)

- **L7Plot Version**: 0.0.3-alpha.6
- **Platform**:

**Comment by fkworld** [comment]
Same problem.

I solved the problem temporarily by locking the `@ant-design/charts` version `1.2.14`.

**Comment by liuvigongzuoshi** [comment]
@zhyupe @fengmk2 Fixed.
