### ISSUE TITLE
🐛 [BUG] 多图表不支持流向图 flow

### ISSUE THREAD

**Issue by zqlu** [antvis/L7Plot#114]
### 🐛 Bug description [Please make everyone to understand it]

高级图表中的多图表 type 不支持配置 flow

> 图表组配置，图表类型支持 L7Plot 内置的图表。

> Please provide a link by forking these links [L7Plot](https://codesandbox.io/s/l7plot-issue-template-ckpvq?file=/src/index.ts) or GitHub repo, a minimal reproduction.

- _Required_ **Link to minimal reproduction**:

### 🚑 Any additional [like screenshots]

- **L7Plot Version**:
- **Platform**:

**Comment by liuvigongzuoshi** [comment]
@zqlu done #115
