### ISSUE TITLE
🤔 [QUESTION] 世界行政地图如何渲染数据

### ISSUE THREAD

**Issue by Sanmws** [antvis/L7Plot#122]
### 🐛 Question description [Please make everyone to understand it]
如何在世界行政地图中添加各个国家渲染的数据？应该是需要一个code，但是没有提供code-国家对照表
https://codesandbox.io/s/magical-chihiro-xvf3y?file=/index.ts
国内的数据格式是{name:"xxx",code:xxx,value:xxx},可以正常渲染

### 🏞 Expected result

正常展示数据

### 🚑 Any additional [like screenshots]

- **L7Plot Version**:1.3.4
- **Platform**:macos 11

**Comment by liuvigongzuoshi** [comment]
1. 根据名称匹配渲染

```js
{
  source: {
    data: [{ cityName: '上海市', code: 310000, value: 200 }],
    joinBy: {
      sourceField: 'code',
      geoField: 'adcode',
    },
  },
}
```

2. 根据行政编码匹配渲染

```js
{
  source: {
    data: [{ cityName: '上海市', code: 310000, value: 200 }],
    joinBy: {
      sourceField: 'cityName',
      geoField: 'name',
    },
  },
}
```

[文档](https://l7plot.antv.vision/zh/docs/api/plots/choropleth#code-classlanguage-textoptionscodesource) 

@Sanmws
