### ISSUE TITLE
🐛 [BUG]limitInPlot属性无法屏蔽一些后出现的状态

### ISSUE THREAD

**Issue by qiansheng1989** [antvis/L7Plot#123]
limitInPlot属性无法屏蔽一些后出现的状态
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [L7Plot](https://codesandbox.io/s/l7plot-issue-template-ckpvq?file=/src/index.ts) or GitHub repo, a minimal reproduction.

- _Required_ **Link to minimal reproduction**:

### 📷 Step to reproduce
  limitInPlot: true  设置了屏蔽图表外的显示但是折线图的active还是会显示
### 🏞 Expected result
 坐标轴以外的不显示
### 🚑 Any additional [like screenshots]
![1642474629461_1642413791463_9885C938-B913-4d68-93D8-070A8EC6C68C](https://user-images.githubusercontent.com/37897917/149888791-4665b550-7a27-42da-a0ab-3360a3a99452.png)

- **L7Plot Version**:
- **Platform**:

**Comment by liuvigongzuoshi** [comment]
@qiansheng1989 这是 G2Plot ? 到 G2Plot 仓库提 [Issue](https://github.com/antvis/G2Plot/issues/)
