### ISSUE TITLE
行政区域图Choropleth关于选中问题🤔 [QUESTION]

### ISSUE THREAD

**Issue by a1b22003001** [antvis/L7Plot#128]
在行政区域图Choropleth中，在设置了state.select下，能否手动设置城市让地图中相应的位置设置选中状态，操作流程是，前端界面上有一个下拉框，当选择某一城市时，地图上相应的城市区域会显示选中状态。

**Comment by liuvigongzuoshi** [comment]
TODO: [enhancement](https://github.com/antvis/L7Plot/blob/main/packages/l7plot/src/layers/area-layer/index.ts#L330)

**Comment by a1b22003001** [comment]
我试了使用这个setSelect,尝试了使用choropleth.source.originData.features的数据index与地区的adcode,但是并没有效果，请问这个id的参数是怎么从数据中获取，调用setSelect方式后是否还需要调用其他函数刷新界面

**Comment by xiwadai** [comment]
可以使用drillDown或者changeView，对应上adcode来实现下拉城市，地图更新到对应城市展示

**Comment by xiwadai** [comment]
可以使用drillDown或者changeView，对应上adcode来实现下拉城市，地图更新到对应城市展示

**Comment by lvisei** [comment]
这个功能已经上线很久了，就关闭了 #250
