### ISSUE TITLE
🐛 [BUG] L7plot的实例上没有暴露L7上的 getZoom , getCenter ,  setZoomAndCenter 等方法

### ISSUE THREAD

**Issue by BeliefRC** [antvis/L7Plot#129]
L7plot的实例上没有暴露L7上的 getZoom , getCenter ,  setZoomAndCenter 等方法

 [Link](https://codesandbox.io/s/fancy-fire-lkeik0?file=/src/index.ts:1136-1152) 

- **L7Plot Version**:
0.0.5

**Comment by liuvigongzuoshi** [comment]
yep，可通过 plot 拿到 scene，然后调用 scene 方法

```js
// 通过实例
const scene = plot.scene
// 或
const scene = plot.getScene()

plot.on('loaded', () => {
	scene.getZoom() .
	// ...
})
```

@BeliefRC
