### ISSUE TITLE
石油行业的点位图和地理剖面图使用哪种antv工具库图例？

### ISSUE THREAD

**Issue by sunxia628** [antvis/L7Plot#137]
### 🐛 Question description [Please make everyone to understand it]
石油行业的地理剖面图使用哪种antv工具库？

### 💻 Link to minimal reproduction
类似https://www.int.com/geotoolkit-demos/deviated-schematics/图例的偏差示意图，antv有没有替代工具？
我的原型图如下：
![u166](https://user-images.githubusercontent.com/26341016/157827094-51e2f5be-de7f-4249-996e-5d5347288fa2.png)
![u265](https://user-images.githubusercontent.com/26341016/157827097-666213f4-e030-4fbb-9cdf-345f1772300a.png)
在antv的示例中似乎找不到合适的解决方案？

Please provide a link by forking these links [L7Plot](https://codesandbox.io/s/l7plot-issue-template-ckpvq?file=/src/index.ts) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

- **L7Plot Version**:
- **Platform**:

**Comment by sunxia628** [comment]
@susiwen8 为何给关了，也没个说明？

**Comment by susiwen8** [comment]
你不是在 Apache ECharts 的 issue 里得到答案了吗？
