### ISSUE TITLE
为什么 @antv/layers报红色警告

### ISSUE THREAD

**Issue by Yuki-Zhao** [antvis/L7Plot#154]

**Comment by lvisei** [comment]
复现一下问题，提供一个线上 demo @Yuki-Zhao

**Comment by lvisei** [comment]
> 请问antv/l7-layers，这个库是开源的吗？没有在github上搜到

使用最新版 L7Plot 不需要单独装 antv/l7-layers 的 @Yuki-Zhao 
> antv/l7-layers 属于 antv/l7 , 直接装 antv/l7 就是
