### ISSUE TITLE
🐛 [BUG]官方demo choropleth图层事件绑定报错

### ISSUE THREAD

**Issue by JackHlw** [antvis/L7Plot#155]
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [L7Plot](https://codesandbox.io/s/l7plot-issue-template-ckpvq?file=/src/index.ts) or GitHub repo, a minimal reproduction.

- _Required_ **Link to minimal reproduction**:

### 📷 Step to reproduce
![image](https://user-images.githubusercontent.com/26327380/162393449-c3bed971-1292-43bf-845b-3ece0977a913.png)

### 🚑 Any additional [like screenshots]

- **L7Plot Version**:
- **Platform**:

**Comment by lvisei** [comment]
```
choropleth.on('loaded', () => {
	choropleth.on('fillAreaLayer:click', (e: MouseEvent) => {
	
	})
})
```

@JackHlw
