### ISSUE TITLE
🥰 [L7Plot 实例多图表的情况下，没有changeData方法，调用instanceRef.current.update()也不生效]，不过机智的我解决了

### ISSUE THREAD

**Issue by mengbo-ji** [antvis/L7Plot#167]
### 💻 Features description [Please make everyone to understand it]
希望 L7Plot 类添加changeData方法，
### 🏞 What problem does this feature solve
<img width="764" alt="image" src="https://user-images.githubusercontent.com/54396390/165464531-a2305a6e-11e0-4d68-8fc0-f7a3d620afc8.png">

### 🧐 What does the proposed API look like
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/54396390/165464483-b3582f90-18a2-4b7c-9216-279b5db98aca.png">

### 🚑 Any additional [like screenshots]
我只能通过，上面的方式来更新数据

**Comment by lvisei** [comment]
@mengbo-ji you 有[方法](https://l7plot.antv.vision/zh/docs/api/advanced-plot#getplots)获取实例更新的，确实全量更新的 API 还不支持

![image](https://user-images.githubusercontent.com/26923747/165663515-c5de15d7-b960-4949-9f6d-ef24caa3c560.png)
