### ISSUE TITLE
🤔 [QUESTION] new L7Plot 通过点击事件怎么获取到点击区域的值（'choropleth' 或 'dot'）

### ISSUE THREAD

**Issue by LipiAndPili** [antvis/L7Plot#169]
### 🐛 Question description [Please make everyone to understand it]
https://l7plot.antv.vision/zh/examples/advanced-plot/muti-plots#china-bubble

![image](https://user-images.githubusercontent.com/50241817/167107984-4f9f0019-0157-4b60-a240-db726c5cbdf5.png)

### 💻 Link to minimal reproduction

Please provide a link by forking these links [L7Plot](https://codesandbox.io/s/l7plot-issue-template-ckpvq?file=/src/index.ts) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🏞 Expected result

通过点击区域或点获取到当前的数据

### 🚑 Any additional [like screenshots]

- **L7Plot Version**:
- **Platform**:

**Comment by lvisei** [comment]
```js
plot.on('loaded', () => {
      const choropleth = plot.getPlotByName('choropleth')
      choropleth.on('loaded', () => {
        choropleth.on('fillAreaLayer:click', ee => {
        console.log(ee)
      })
   })
})
```

[🔗](https://codesandbox.io/s/rx18kx?file=/index.ts)

@LipiAndPili
