### ISSUE TITLE
🐛 [BUG]警告Too many active WebGL contexts. Oldest context will be lost.

### ISSUE THREAD

**Issue by xiaochong44** [antvis/L7Plot#172]
### 🐛 警告Too many active WebGL contexts. Oldest context will be lost.

用官网的例子多次修改配置信息会出现警告Too many active WebGL contexts. Oldest context will be lost.
我自己的代码也同样的问题，已经在组件卸载的时候调用了destroy

- **L7Plot Version**:0.0.11
- **Platform**:vue

**Comment by JackHlw** [comment]
请问这个问题有修复计划吗 @2912401452 @lvisei

**Comment by lvisei** [comment]
> 请问这个问题有修复计划吗 @2912401452 @lvisei

应该是图层没有完全 destroy，优先级较低，@2912401452 排期来搞
