### ISSUE TITLE
🤔 [QUESTION] 如何实现中国地图的七大地理分区，并在分区上面显示分区名字和数据

### ISSUE THREAD

**Issue by LipiAndPili** [antvis/L7Plot#177]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [L7Plot](https://codesandbox.io/s/l7plot-issue-template-ckpvq?file=/src/index.ts) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🏞 Expected result
![image](https://user-images.githubusercontent.com/50241817/171139248-44069b78-bc14-4d3d-8bda-f07b8928dc5b.png)

### 🚑 Any additional [like screenshots]

- **L7Plot Version**:
- **Platform**:

**Comment by lvisei** [comment]
自定义数据实现

https://l7plot.antv.vision/zh/examples/area/division#chinese-citys

@LipiAndPili
