### ISSUE TITLE
🤔 [QUESTION]请问label支持动态的吗

### ISSUE THREAD

**Issue by wjjhhh** [antvis/L7Plot#182]
1、例如label原本是广州市，但需求要数据结合，如广州市（999）。
2、甚至能支持组件形式，可以自己封装改样式

**Comment by lvisei** [comment]
label 目前只能指定单个数据字段，如果需要结合，数据先遍历处理一下，label 是文本样式，不支持自定义组件；如果需要使用图表外的更多能力，可以使用 L7 MarkerLayer
