### ISSUE TITLE
🤔 [QUESTION]是否支持自动选中地区

### ISSUE THREAD

**Issue by wjjhhh** [antvis/L7Plot#185]
有这样一个场景，外面有个地区列表，在列表中选中广州，地图就自动选中到广州

还有请问有相关沟通群吗，我问题挺多的🤔

**Comment by xiwadai** [comment]
同样遇到这个问题，下列列表里面是各个省选中某一个省这个该怎样更新到对应的省的地图

**Comment by lvisei** [comment]
https://l7plot.antv.vision/zh/examples/choropleth/administrative#administrative-switch

@wjjhhh @xiwadai
