### ISSUE TITLE
钻取地图地市后 地图lable 显示问题🐛 [BUG]

### ISSUE THREAD

**Issue by zxc-cool** [antvis/L7Plot#190]
### 🐛 Bug description [Please make everyone to understand it]

![image](https://user-images.githubusercontent.com/38719680/174994484-88c80a6a-50b3-4bad-8b9a-6752fe5bb139.png)

![image](https://user-images.githubusercontent.com/38719680/174994569-dbd3e21c-3d10-4b83-bbac-608e1e1b67ea.png)

### 🚑 Any additional [like screenshots]

- **L7Plot Version**:
- **Platform**:

**Comment by lvisei** [comment]
@zxc-cool 提供在线示例

**Comment by wozien** [comment]
+1
