### ISSUE TITLE
🤔 行政区域图Choropleth不能离线使用？不联网状态下如何载入初始的图json依赖数据？

### ISSUE THREAD

**Issue by lyl620** [antvis/L7Plot#200]
### 🐛 Question description
  行政区域图地理数据需要默认线上载入数据，官网默认配置如下：
geoArea: {
    url: 'https://gw.alipayobjects.com/os/alisis/geo-data-v0.1.2/choropleth-data',
    type: 'topojson',
  },
我已经通过下载地图依赖json文件，本地建了相似的choropleth-data文件夹，此时将geoArea配置中的URL改为本地/项目的choropleth-data文件夹地址，都失效。

请问，行政图功能如何载入依赖的json文件夹？

**Comment by lvisei** [comment]
行政数据 [choropleth-data](https://www.jsdelivr.com/package/npm/static-geo-atlas?path=geo-data%2Fchoropleth-data) 

下载之后部署成静态文件服务，修改 geoArea.url 配置访问文件夹 HTTP 服务地址
