### ISSUE TITLE
🤔 [QUESTION]

### ISSUE THREAD

**Issue by huyanhu6261** [antvis/L7Plot#201]
怎么获取缩放下四个角的经纬度

**Comment by huyanhu6261** [comment]
怎么获取缩放下四个角的经纬度

**Comment by lvisei** [comment]
拿到[地图实例](https://l7plot.antv.vision/zh/docs/api/plot-api#getmap)，通过方法获取

```
const map = plot.getMap()

// 配置的 
```

使用不同的底图，map 上的方法不一致，比如 amap 是 [getBounds()](https://lbs.amap.com/api/javascript-api/reference/map)，详见各底图开发者使用文档，
