### ISSUE TITLE
🐛 [BUG]  行政区域图-Choropleth，更新fontFamily不生效

### ISSUE THREAD

**Issue by liuguanyu** [antvis/L7Plot#202]
### 🐛 Bug description

Choropleth 区域行政图，对于textLayer，如label。当有切换字体的需求时，字体切换失败。同样的方法对字体大小是生效的。
希望能够实现字体切换

[复现地址](https://codesandbox.io/s/proud-silence-2zmd7g)

### 📷 复现步骤：

1.  建立Choropleth
2. 变更字号，其实是修改：config.label.style.fontSize ，然后调用plot.update，可以成功
3. 变更字体，其实是修改：config.label.style.fontFamily，然后调用plot.update， 失败，而且之前已经调用了 @antv/l7plot 的 registerFontFace 

### 🏞 希望结果
能够实现字体切换

### 🚑 截图 

![](https://p0.ssl.qhimg.com/t0112795e0d7b3629b1.png)

- **L7Plot Version**:  0.1.0
- **Platform**: any

**Comment by CodingAndSleeping** [comment]
我也遇到了这个情况，同样的操作 更新 config.label.style.textAllowOverlap 属性也不生效

**Comment by lvisei** [comment]
文本注册字体 addFontFace API 底层实现逻辑，本质上还是

```html
<style type="text/css">
  @font-face {
    font-family:"My Font";
    src:url("assets/fonts/my_font.woff") format("woff");
	font-style: normal;
	font-weight: normal; /* or 400 */
  }
</style>
```

故在渲染之前确保字体资源已经注册完成，确保字体资产注册完成的库 https://github.com/typekit/webfontloader

**Comment by lvisei** [comment]
> 我也遇到了这个情况，同样的操作 更新 config.label.style.textAllowOverlap 属性也不生效

textAllowOverlap 是否允许文字遮盖是文字边框碰撞检测，不生效提供 demo 复现一下

**Comment by CodingAndSleeping** [comment]
> > 我也遇到了这个情况，同样的操作 更新 config.label.style.textAllowOverlap 属性也不生效
> 
> textAllowOverlap 是否允许文字遮盖是文字边框碰撞检测，不生效提供 demo 复现一下

https://codesandbox.io/p/sandbox/trusting-paper-djtv72?file=%2Fsrc%2Fcomponents%2FMap.vue%3A39%2C19
