### ISSUE TITLE
🤔 [QUESTION]请问区域图中label的textAnchor为何不起作用

### ISSUE THREAD

**Issue by lxlxue** [antvis/L7Plot#210]
### 💻 Link to minimal reproduction

![image](https://user-images.githubusercontent.com/21966423/186365492-74bca3b0-25f3-4f92-9653-392d9c5b3d99.png)
label中的textAnchor设置为top-right，但并没有产生效果，label的定位还是center。请问这是为什么呢
### 🚑 Any additional [like screenshots]

- **L7Plot Version**:0.1.0
- **Platform**:vue

**Comment by lvisei** [comment]
相对位置不明显可以手动调整 textOffset
