### ISSUE TITLE
🤔 [QUESTION]对应地图请注册Token？？？上哪里注册token呀

### ISSUE THREAD

**Issue by chrisRen** [antvis/L7Plot#212]
您正在使用 Demo测试地图token，如果生产环境中使用去对应地图请注册Token
上哪里注册token呀

**Comment by FourLeafClover** [comment]
使用高德地图就去高德地图开发平台申请，使用mapbox就去mapbox'官网申请。

**Comment by wozien** [comment]
为啥自定义的token不能使用 blank 主题

**Comment by lvisei** [comment]
> 为啥自定义的token不能使用 blank 主题

自定义的 token 需要到高德地图开发平台去配置底图样式，blank 是 L7 内置默认 token 配置主题
