### ISSUE TITLE
🐛 [BUG] 行政区域图 Choropleth 在使用 Vite 构建的项目中下钻不显示标签

### ISSUE THREAD

**Issue by iamdhj** [antvis/L7Plot#215]
### 🐛 Bug description 
在 Vite 构建的 Vue3 项目中使用行政区域图 Choropleth，下钻操作标签没有同步切换，还是显示全国级别的标签。
[问题示例](https://codesandbox.io/s/choropleth-drill-demo-qeb9bu?file=/src/App.vue)

### 📷 Step to reproduce
1. 点击任一省份
2. 区域切换，下级标签不显示

### 🏞 Expected result
下钻操作，显示下级标签

### 🚑 Any additional 
国内镜像 [区域钻取|L7](https://antv-l7.gitee.io/zh/examples/choropleth/drill#order-drill) 表现正常
国际站 [区域钻取|L7](https://l7.antv.vision/zh/examples/choropleth/drill#order-drill) 也有同样的问题
![image](https://user-images.githubusercontent.com/6936831/188270308-cc3588b4-1394-44d7-a187-bd77fef88720.png)

- **L7Plot Version**: 0.1.0
- **Platform**: Windows 10

**Comment by lvisei** [comment]
删除缓存，使用最新依赖，未曾复现
https://l7plot.antv.vision/zh/examples/choropleth/drill#order-drill

**Comment by iamdhj** [comment]
排查发现是  l7-source 在 2.9.19 版本删除了  `setData` 方法内的 `update` 事件通知，改为在 `init` 方法内增加 `sourceUpdate` 事件通知 
[提交记录](https://github.com/antvis/L7/commit/6a04210de6f36562839851bf4738ff4313ad6621/packages/source/src/source.ts#diff-2a3b1f9ef438b279d7defbbdf43b89af2247bfb03793f086201f3e55260514e7L191)

所以行政区域图添加标签图层设置的更新事件监听器无法触发
https://github.com/antvis/L7Plot/blob/ced5418927717b98edf39eea9abc84bd7ee86a7b/packages/l7plot/src/plots/choropleth/index.ts#L281-L288

[上面提供的示例](https://github.com/antvis/L7Plot/issues/215#issuecomment-1238094626) 执行提示缺少 @antv/l7-core 依赖，增加 @antv/l7 依赖后进行下钻操作有同样的问题

**Comment by hang1017** [comment]
你好。请问下这个问题现在解决了没呢。

**Comment by lvisei** [comment]
cc @yiiiiiiqianyao

**Comment by yiiiiiiqianyao** [comment]
@lvisei 是事件名替换了，数据更新同样会触发
