### ISSUE TITLE
🐛 [BUG] 首次加载时图例不显示

### ISSUE THREAD

**Issue by satouriko** [antvis/L7Plot#224]
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [L7Plot](https://codesandbox.io/s/l7plot-issue-template-ckpvq?file=/src/index.ts) or GitHub repo, a minimal reproduction.

- _Required_ **Link to minimal reproduction**: https://l7.antv.vision/zh/examples/choropleth/administrative#zhejiang-province

### 📷 Step to reproduce

官方文档中的示例是有设置选项
```
        legend: {
          position: 'bottomleft',
        },
```
但是图例不显示

### 🚑 Any additional [like screenshots]
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/18373361/193195262-9ef3708a-784d-41de-9203-e3282423966c.png">

- **L7Plot Version**:
- **Platform**:

**Comment by lvisei** [comment]
@satouriko 使用最新版 `@antv/l7plot  0.3.3`
