### ISSUE TITLE
🤔 [QUESTION]L7plot能实现选择不同的城市行政区域，然后展示不同城市区域的热力图嘛

### ISSUE THREAD

**Issue by 918xijiji** [antvis/L7Plot#225]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [L7Plot](https://codesandbox.io/s/l7plot-issue-template-ckpvq?file=/src/index.ts) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

- **L7Plot Version**:
- **Platform**:

**Comment by lvisei** [comment]
属于自定义需求，城市切换更新数据显示不同城市的热力图
