### ISSUE TITLE
🐛 [BUG] 行政区域图 Choropleth 在使用umi/alita项目中下钻不显示标签显示错误

### ISSUE THREAD

**Issue by hang1017** [antvis/L7Plot#230]
![image](https://user-images.githubusercontent.com/48704410/195748613-f9263133-efa6-4587-98a7-a8d58a2c4ce6.png)

[map.zip](https://github.com/antvis/L7Plot/files/9781981/map.zip)

复现流程：
pnpm i 
pnpm start
访问：http://localhost:8000/#/lMap

**Comment by xiaohuoni** [comment]
和 umi 无关，用 cra 跑一样的 问题
![image](https://user-images.githubusercontent.com/11746742/195782042-ddc720d1-2b4f-4bf9-b3dd-f614e3a41538.png)

**Comment by lvisei** [comment]
@hang1017 删掉依赖，安装最新版，L7 事件已经恢复

#215
