### ISSUE TITLE
🐛 [BUG] 图标示例里面的示例全显示不出来，控制台提示报错

### ISSUE THREAD

**Issue by zhou10759** [antvis/L7Plot#236]
[

### 🐛 示例里面的示例全显示不出来，控制台提示报错

![image](https://user-images.githubusercontent.com/43510395/197728227-e3f84448-cfd9-4b45-a63d-2ca49f2e1e8f.png)

- **L7Plot Version**:
- **Platform**:

**Comment by lvisei** [comment]
@zhou10759 未曾复现 https://l7plot.antv.vision/zh/examples/dot/icon#poi
