### ISSUE TITLE
🐛 [BUG]行政区域图开启下钻功能配置双击事件触发下钻无效

### ISSUE THREAD

**Issue by LOCKD2016** [antvis/L7Plot#239]
### 🐛 Bug description [Please make everyone to understand it]
行政区域图Choropleth开启drill属性 , 配置triggerDown为dblclick , 双击省份区域无法下钻 , 默认click事件触发正常

> Please provide a link by forking these links [L7Plot](https://codesandbox.io/s/l7plot-issue-template-ckpvq?file=/src/index.ts) or GitHub repo, a minimal reproduction.

https://antv-l7.gitee.io/zh/examples/choropleth/administrative#china-map

- _Required_ **Link to minimal reproduction**:

### 🚑 Any additional [like screenshots]

- **L7Plot Version**:0.2.0
- **Platform**:windows

**Comment by lvisei** [comment]
@LOCKD2016 
下钻 [drill](https://l7plot.antv.vision/zh/docs/api/plots/choropleth#code-classlanguage-textoptionscodedrill) 路径未配置

https://antv-l7.gitee.io/zh/examples/choropleth/drill#order-drill
