### ISSUE TITLE
🤔 [QUESTION]行政区域：获取没有区县的地市的地理数据为空

### ISSUE THREAD

**Issue by JiangLinsheng** [antvis/L7Plot#256]
### 🐛 行政区域，获取没有区县的地市的地理数据为空，包括广东省： 东莞市（441900）、中山市（442000）；海南省： 儋州市（460400）；甘肃省 ：嘉峪关市（620200）。
例如请求东莞市的地理数据的接口url如下：
https://gw.alipayobjects.com/os/alisis/geo-data-v0.1.2/choropleth-data/city/441900_city_district.topo.json

接口返回如下：
![image](https://user-images.githubusercontent.com/45457209/203969984-39c6d779-0dc6-4f57-a3db-d72effd4d10e.png)

代码片段如下：
![image](https://user-images.githubusercontent.com/45457209/203970568-bb7f0531-68e4-4c88-8c5c-7f0cfc06c654.png)

此地址拿到的地理数据也是为空的，地址为：
https://cdn.jsdelivr.net/npm/static-geo-atlas@0.0.2/geo-data/choropleth-data/city/441900_city_district.topo.json
截图如下：
![image](https://user-images.githubusercontent.com/45457209/203971464-162077f3-b843-4d2c-aaa8-4f8f719a86dd.png)

希望大佬可以抽出宝贵的时间帮小弟看看。

**Comment by lvisei** [comment]
东莞市下面没有区县数据，直接是街道粒度，所以没有数据，geo-data 里面没有处理这种情况，如果有需要自己提供数据吧，替换成自己的数据 URL 地址
@JiangLinsheng
