### ISSUE TITLE
🐛 [BUG]行政区图层的所有函数都使用不了

### ISSUE THREAD

**Issue by xixiqnmb** [antvis/L7Plot#268]
行政区图层的所有函数都使用不了，是我的使用问题还是bug

![image](https://user-images.githubusercontent.com/67090743/213124733-7c9367d3-bb6f-408c-9749-2a7179c63a68.png)

- **L7Plot Version**:
- **Platform**:

**Comment by lvisei** [comment]
@xixiqnmb 提供

实例化完成后，需加载完成对实例操作
```js
plot.on('loaded', callback: (...args) => void);
```
