### ISSUE TITLE
🐛 [BUG]台湾省，行政级别颗粒度是district（区县）时，地图无法正确加载

### ISSUE THREAD

**Issue by aimerthy1** [antvis/L7Plot#269]
![image](https://user-images.githubusercontent.com/44153856/215393269-8c593dde-910b-4099-9ed8-26c5215e0759.png)
[复现链接](https://codesandbox.io/s/hardcore-jackson-4fhpyg?file=/index.ts)
把granularity改成city是可以看到台湾省的，但是改成district，地图就无法正确显示

**Comment by lvisei** [comment]
默认[使用的数据](https://l7plot.antv.antgroup.com/api/plots/choropleth#optionsgeoarea)，没有台湾省下的区县数据，如有需要自己提供数据。

**Comment by aimerthy1** [comment]
我要怎么提供数据呀

**Comment by lvisei** [comment]
> 我要怎么提供数据呀，有没有实例代码看看

可下载后补充数据，配置自己的数据地址，台湾省的看网上有没有

![image](https://user-images.githubusercontent.com/26923747/215680539-c3bfb006-37a2-4aed-b9e4-c5c1fc492474.png)
