### ISSUE TITLE
在l7plot中设置填充兜底颜色-fillBottomColor，控制台报错

### ISSUE THREAD

**Issue by mwq216** [antvis/L7Plot#273]
![image](https://user-images.githubusercontent.com/16487008/219340520-ed6ae1d0-5c86-4141-8444-70006763759f.png)
这是代码，是最近才出现的问题。之前还是可以正常使用的，插件没有做升级，不知道为突然提示错误了
![image](https://user-images.githubusercontent.com/16487008/219340942-f09f793f-94b8-4fb9-b5de-ad6ac1cd18d9.png)

**Comment by mwq216** [comment]
那如果想设置兜底颜色是否有新的方法呢？

**Comment by lvisei** [comment]
```js
{
  color: {
    field: 't',
    value: ['#B8E1FF', '#7DAAFF', '#3D76DD', '#0047A5', '#001D70'],
    scale: { type: 'quantile', unknown: '#c0c0c0' }
  }
}

```

**Comment by mwq216** [comment]
多谢多谢，我看api文档上也有标注，之前忽略了
