### ISSUE TITLE
🤔 [QUESTION] 可以添加一个RasterLayer的使用demo吗

### ISSUE THREAD

**Issue by Euraxluo** [antvis/L7Plot#285]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [L7Plot](https://codesandbox.io/s/l7plot-issue-template-ckpvq?file=/src/index.ts) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

- **L7Plot Version**:
- **Platform**:

**Comment by lvisei** [comment]
请使用 LarkMap https://larkmap.antv.antgroup.com/components/layers/base-layers/raster-layer
