### ISSUE TITLE
🐛 [BUG] Choropleth 无法绑定事件

### ISSUE THREAD

**Issue by notcold** [antvis/L7Plot#310]
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [L7Plot](https://codesandbox.io/s/l7plot-issue-template-ckpvq?file=/src/index.ts) or GitHub repo, a minimal reproduction.

https://codesandbox.io/s/serene-nightingale-nylzx7?file=/index.ts

- _Required_ **Link to minimal reproduction**:

### 📷 Step to reproduce
![image](https://github.com/antvis/L7Plot/assets/16741847/7fa2ab1b-29b1-4e29-bcda-1482af33bb46)

### 🚑 Any additional [like screenshots]

- **L7Plot Version**:
![image](https://github.com/antvis/L7Plot/assets/16741847/2a457e81-f62d-4588-9d1a-cf38328b34da)

- **Platform**:

**Comment by lvisei** [comment]
after addToScene @notcold 

```js
choropleth.addToScene(scene);
choropleth.on("click", (e) => {
  console.log(e);
});
```
