### ISSUE TITLE
🐛 [BUG] 官网样例展示报错，https://l7plot.antv.antgroup.com/zh/examples/choropleth/administrative/#china-map

### ISSUE THREAD

**Issue by qxang** [antvis/L7Plot#311]
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [L7Plot](https://codesandbox.io/s/l7plot-issue-template-ckpvq?file=/src/index.ts) or GitHub repo, a minimal reproduction.

- _Required_ **Link to minimal reproduction**:

### 🚑 Any additional [like screenshots]

- **L7Plot Version**:
- **Platform**:
- 截图
- 
![image](https://github.com/antvis/L7Plot/assets/8686640/0fa1b21e-39ae-40f1-9c18-c0979411f0a2)

**Comment by qxang** [comment]
本地更新最新版本，也有相同问题

**Comment by qxang** [comment]
### _****_

**Comment by lvisei** [comment]
@qxang 安装最新版本 @antv/l7，官网已经修复
