### ISSUE TITLE
行政区域图Choropleth中，如何对每一个label的位置进行调整呢？

### ISSUE THREAD

**Issue by HaLoJJ** [antvis/L7Plot#318]
行政区域图Choropleth中，因为有一些地方区域较小，导致相邻的地方名会重叠，现在想对具体的地方的label进行位置的调整，如何对每一个label的位置进行调整呢？

**Comment by lvisei** [comment]
建议加文本碰撞检测 [label.style.padding ](https://l7plot.antv.antgroup.com/api/components/label)

**Comment by lvisei** [comment]
![image](https://github.com/antvis/L7Plot/assets/26923747/c48901ee-9016-4908-bcc5-c9623e239e39)

可自行指定文本经纬度位置哈
