### ISSUE TITLE
🤔 [QUESTION] Choropleth + drill 使用callback 进行点击省市区进行异步加载数据

### ISSUE THREAD

**Issue by Peter-FrontEnd** [antvis/L7Plot#322]
老哥 辛苦问下

如何使用其他方法 更新省市区的value值 映射色块更新

我用了changeData 并不生效 (视角在中国 直接使用changeData更新)

this.chorLayer.changeData({
       data:this.provinceData,
 })

不生效并且报错
Uncaught (in promise) TypeError: data.forEach is not a function

麻烦老哥了

**Comment by Peter-FrontEnd** [comment]
@lvisei  hello 有时间吗 哥

**Comment by lvisei** [comment]
codesanbox 上复现一下问题
