### ISSUE TITLE
🤔 [QUESTION]除amap外，map/mapbox在下钻回退过程中，地图轮廓短暂滞留

### ISSUE THREAD

**Issue by hewitt99** [antvis/L7Plot#328]
### 🐛 Question description 
如题，在下钻过程中，发现中国chinaBorder会有短暂的滞留。
### 💻 Link to minimal reproduction
复现：将map类型更改为map
[官网地址](https://l7plot.antv.vision/examples/choropleth/drill/#order-drill)

### 🏞 Expected result
请问除了用amap外，对于这种滞留情况，有推荐的解决办法吗？
### 🚑 Any additional [like screenshots]
![录屏2023-10-25 15 11 13](https://github.com/antvis/L7Plot/assets/81789871/29fb90aa-a8a8-403e-ad25-e950c32395b3)
- **L7Plot Version**:
- **Platform**:

**Comment by lvisei** [comment]
@hewitt99 看上去是 map 视角切换卡顿的问题，有时间的话可以帮忙排除修一下

**Comment by lvisei** [comment]
map 是有问题的，可以替换为 mapbox, style 设置为 blank

**Comment by lvisei** [comment]
升级到最新版本 L7，这个问题已经解决了
