### ISSUE TITLE
🐛 [BUG] 官网疯狂抖动

### ISSUE THREAD

**Issue by zhengmenghuang** [antvis/L7Plot#332]
![image](https://github.com/antvis/L7Plot/assets/29627098/d90f9bc7-75ae-414b-bb30-fdbcf89b2e5f)

https://github.com/antvis/L7Plot/assets/29627098/4a136797-9ab5-485d-87ef-59a47b6bb814

https://l7plot.antv.vision/zh/examples/choropleth/drill/#order-drill

鼠标放到如图位置 官网会疯狂抖动

**Comment by lvisei** [comment]
为复现

**Comment by zhengmenghuang** [comment]
> 未复现

windows 11
Chrome 119

你在试一下 我这里还是会抖动

**Comment by topul** [comment]
用edge浏览器，打开侧边栏或垂直标签页，就可以复现了
