### ISSUE TITLE
🐛 [BUG] 英文字体有问题

### ISSUE THREAD

**Issue by liho00** [antvis/L7Plot#333]
### 🐛 Bug description [Please make everyone to understand it]
英文字体不整齐，设置了fontFamily也不行

https://l7plot.antv.vision/examples/area/division#us-states-density
<img width="478" alt="image" src="https://github.com/antvis/L7Plot/assets/77238199/0b5e523f-f45b-4c28-b243-5e6e13909dd1">

正常字体
https://ant-design-charts.antgroup.com/examples/map-area/division#us-states-density
<img width="492" alt="image" src="https://github.com/antvis/L7Plot/assets/77238199/daded341-a9de-4fbc-872b-f2cd77778b79">

> Please provide a link by forking these links [L7Plot](https://codesandbox.io/s/l7plot-issue-template-ckpvq?file=/src/index.ts) or GitHub repo, a minimal reproduction.

- _Required_ **Link to minimal reproduction**:

### 📷 Step to reproduce

```
label: {
              visible: true,
              field: "shapeName",
              style: {
                fontFamily: "Poppins",
                fontWeight: 900,
                opacity: 1,
                fill: prefersDarkMode ? "#fff" : "#000",
                opacity: 1,
                fontSize: lg ? 10 : 8,
                textAllowOverlap: false,
                fontWeight: 500,
                gamma: 2,
                // strokeOpacity: 0.5,
                // strokeWidth: 0.1,
                // stroke: "#fff",
                padding: [8, 8],
              },
            },
```

### 🏞 Expected result
正常且整齐的英文字母 

### 🚑 Any additional [like screenshots]

- **L7Plot Version**:
- **Platform**:
```
    "@ant-design/maps": "^1.0.7",
    "@antv/l7": "^2.19.9",
    "@antv/l7-district": "^2.3.12",
    "@antv/l7-maps": "^2.19.9",
    "@antv/l7plot": "0.3.3",
```

**Comment by Jerome-lara** [comment]
这个修复了嘛？好像没有。
