### ISSUE TITLE
🤔 [QUESTION] 行政区域切换 地图手动下钻 或 自动下钻

### ISSUE THREAD

**Issue by Peter-FrontEnd** [antvis/L7Plot#334]
场景 下拉+用户手动点击地图  都可以实现下钻或者上卷操作

changeView 和 drill 是否同时支持呢 我试了下好像并不能 调用不到onDown方法

**Comment by lvisei** [comment]
changeView 可以随意改变下钻路径，目前两个是分开的，逻辑上不好实现
