### ISSUE TITLE
🐛 [BUG]legend.domStyles该配置l7plot-legend__category设置不生效

### ISSUE THREAD

**Issue by Danihay** [antvis/L7Plot#339]
https://l7plot.antv.antgroup.com/api/components/legend#legenddomstyles
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [L7Plot](https://codesandbox.io/s/l7plot-issue-template-ckpvq?file=/src/index.ts) or GitHub repo, a minimal reproduction.
![image](https://github.com/antvis/L7Plot/assets/19901256/3572eec2-e174-42e0-86c2-4cedf2ad2d1b)

- _Required_ **Link to minimal reproduction**:

### 🚑 Any additional [like screenshots]

- **L7Plot Version**:
- **Platform**:

**Comment by lvisei** [comment]
看了下源码应该是这样写，如果有时间的话，欢迎提 PR 帮忙改下文档
```
'l7plot-legend l7plot-legend__category'?: CSSProperties
```

https://github.com/antvis/L7Plot/blob/main/packages/component/src/legend/category/constants.ts
