### ISSUE TITLE
🤔 [QUESTION] label可以设置其是否为斜体吗？ 看文档是没有这个配置项，但是quickBI 上好像也是用的l7，可以设置为斜体 

### ISSUE THREAD

**Issue by CodingAndSleeping** [antvis/L7Plot#341]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [L7Plot](https://codesandbox.io/s/l7plot-issue-template-ckpvq?file=/src/index.ts) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

- **L7Plot Version**:
- **Platform**:

**Comment by lvisei** [comment]
不支持通过样式来写斜体。可以通过注册字体来实现。字体注册参考 #202
