### ISSUE TITLE
🤔 [QUESTION]  行政区划图 Choropleth  能否支持 自定义 行政名称 的映射？

### ISSUE THREAD

**Issue by CodingAndSleeping** [antvis/L7Plot#344]
比如  我的数据是  :
```js
 const data = [
    {
       省: '广西'，
      数量：'100'
    }
 ]
```
这样是识别不了的，必须是广西壮族自治区才可以，有没有什么办法可以自定义名称映射

**Comment by lvisei** [comment]
数据匹配映射规则可根据标准的行政名称或行政编码，https://www.yuque.com/antv/l7/wrxc8h#yyIb，无效数据会导致匹配不上地理数据。不标准的数据，可自己写方法数据改成规范的后再用起来。
