### ISSUE TITLE
🐛 [BUG]面图层 - PolygonLayer不能使用

### ISSUE THREAD

**Issue by 315574925** [antvis/L7Plot#345]
![image](https://github.com/antvis/L7Plot/assets/34641313/9b467d14-63da-4bcb-9825-8738a1a208f9)

![image](https://github.com/antvis/L7Plot/assets/34641313/d71ec6f9-8e8f-404a-8912-08561b14d0e3)
![image](https://github.com/antvis/L7Plot/assets/34641313/e866109d-67b6-4749-a489-83ede2a55678)

**Comment by 315574925** [comment]
@lvisei 可以帮忙看看是我使用问题还是啥问题呢

**Comment by lvisei** [comment]
用错了，L7Plot 是图表没有图层单独的实例。不会用直接用 L7 吧

- 用 L7 https://l7.antv.antgroup.com/examples/polygon/fill/#usa
- 用 L7Plot https://l7plot.antv.antgroup.com/examples/area/division/#us-states-density

**Comment by 315574925** [comment]
> 用错了，L7Plot 是图表没有图层单独的实例。不会用直接用 L7 吧
> 
> * 用 L7 https://l7.antv.antgroup.com/examples/polygon/fill/#usa
> * 用 L7Plot https://l7plot.antv.antgroup.com/examples/area/division/#us-states-density

@lvisei L7Plot 是不能用基础图层里边的图层吗？只能用
![image](https://github.com/antvis/L7Plot/assets/34641313/7f129bcd-a647-4b60-a864-fa8dde974116)
里边的吗

**Comment by lvisei** [comment]
是的，基础图层可以在 L7 上用

**Comment by 315574925** [comment]
> 是的，基础图层可以在 L7 上用

好的，谢谢告知，再请教下大佬一个问题下，就比如我想实现巴中市各个区县及街道区域地图悬浮效果，我是不是只能使用L7去实现呢，因为plot不能使用 PolygonLayer ，我试了试 水晶体图层 - PrismLayer 好像也不是悬浮效果

**Comment by lvisei** [comment]
悬浮效果去看 L7 吧，L7Plot 只是一个简单的地理图表

**Comment by 315574925** [comment]
> 悬浮效果去看 L7 吧，L7Plot 只是一个简单的地理图表

好的，谢谢了
