### ISSUE TITLE
🐛 [BUG] 行政区划图 Choropleth  绘制色彩地图变黑色

### ISSUE THREAD

**Issue by CodingAndSleeping** [antvis/L7Plot#347]
1.新建Choropleth图层
2.数据是正常的省份数据，但是绘制出来变成黑白色

![Snipaste_2024-02-27_10-29-39](https://github.com/antvis/L7Plot/assets/63341670/ceeaceb3-9d16-440c-8189-ce755debbf06)

[demo](https://codesandbox.io/p/sandbox/youthful-james-6jsl5l?file=%2Fsrc%2Fcomponents%2FMap.vue%3A4%2C1)

**Comment by lvisei** [comment]
将数量字段的值改为数值类型即可
