### ISSUE TITLE
🐛 [BUG] 更新后区域填充图出现 Cannot read properties of undefined (reading 'mapService')

### ISSUE THREAD

**Issue by hastings0714** [antvis/L7Plot#353]
近期更新最新版后，会出现 
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'mapService')`

### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [L7Plot](https://codesandbox.io/s/l7plot-issue-template-ckpvq?file=/src/index.ts) or GitHub repo, a minimal reproduction.

- _Required_ **Link to minimal reproduction**:

### 📷 Step to reproduce
![image](https://github.com/antvis/L7Plot/assets/13328882/1668e0dc-5126-4f36-9598-5d3dc349d012)
区域填充demo图可复现

### 🏞 Expected result
处理此控制台报错。

### 🚑 Any additional [like screenshots]

- **L7Plot Version**:
- 最新版
- **Platform**:
- mac m1 13.5.2 (22G91)

**Comment by hinadong** [comment]
又是kpi项目

**Comment by lvisei** [comment]
升级最新版本 L7，应该没有这个问题了

**Comment by hastings0714** [comment]
![image](https://github.com/antvis/L7Plot/assets/13328882/7439cfce-db3b-476b-a029-23d07ed34ab4)
更新到2.22.0了，还是有。

**Comment by lvisei** [comment]
我这边看没有报错

- https://codesandbox.io/s/snowy-surf-3mmzqc?file=/index.ts

官网目前有报错，还没有部署最新版本，且这个报错是一个初始化属性访问问题，不影响功能。

**Comment by hastings0714** [comment]
升级最新版，没问题了。如果用了umi,记得删除.umi文件夹。有可能有缓存问题。
