### ISSUE TITLE
🐛 [BUG] 官网行政区域图打开codesandbox报错

### ISSUE THREAD

**Issue by zhushibo** [antvis/L7Plot#354]
### 🐛 Bug description [Please make everyone to understand it]
打开世界地图的行政区域图demo, 报两种错误
![image](https://github.com/antvis/L7Plot/assets/26269311/894ce998-82ab-4aa4-8110-fea50209a718)

下图是本地，报错内容和codesandbox一样
![image](https://github.com/antvis/L7Plot/assets/26269311/444c447b-5d43-43a2-80b1-a7a766821cbe)

![image](https://github.com/antvis/L7Plot/assets/26269311/d28ecb8e-19a8-43dc-944b-2a5810bd7d44)

### 📷 Step 
打开世界地图的行政区域图

### 🏞 Expected result
正确显示
### 🚑 Any additional [like screenshots]
    "@antv/l7": "^2.21.3",
    "@antv/l7-composite-layers": "^0.16.4",
    "@antv/l7-maps": "^2.21.3",
    "@antv/l7plot": "^0.5.9",

**Comment by lvisei** [comment]
我这边看是没有问题的，升级 "@antv/l7" 至 "^2.22.0"

**Comment by wisonic-s** [comment]
降级 @antv/l7 到 2.21.1 就行了，原因是 L7Plot 编译的 target 是 ES5，L7 是 ES6，ES5 的类没法继承 ES6，可以看我的 PR 本地编译一个替换就没问题了。
